Repository codesquad-gwanaksan/kiosk-max, pull requests merged in 2023-06, with the labels that each got.

#3 [FE] CRA 프로젝트 초기 설정
  .gitmessage.txt
  README.md
  fe/.gitignore
  fe/.prettierrc
  fe/README.md
  fe/package.json
  fe/public/assets/MenuImg/Affogato.png
  fe/public/assets/MenuImg/Americano.png
  fe/public/assets/MenuImg/Apple Beet Juice.png
  fe/public/assets/MenuImg/Apple mango Smoothie.png
  fe/public/assets/MenuImg/Caffe Latte.png
  fe/public/assets/MenuImg/Caffe Mocha.png
  fe/public/assets/MenuImg/Cappuccino.png
  fe/public/assets/MenuImg/Caramel Macchiato.png
  fe/public/assets/MenuImg/Chamomile.png
  fe/public/assets/MenuImg/Chocolate HOT:ICED.png
  fe/public/assets/MenuImg/Cold Brew Delight .png
  fe/public/assets/MenuImg/Cold Brew Latte.png
  fe/public/assets/MenuImg/Earl Grey.png
  fe/public/assets/MenuImg/Espresso.png
  fe/public/assets/MenuImg/Goheung Yuzu Tea.png
  fe/public/assets/MenuImg/Gold Pineapple Tropical Smoothie.png
  fe/public/assets/MenuImg/Green Grape Kale Juice.png
  fe/public/assets/MenuImg/Green Grape SPARKLING .png
  fe/public/assets/MenuImg/Green Tea.png
  fe/public/assets/MenuImg/Jeju Matcha Latte.png
  fe/public/assets/MenuImg/Latte.png
  fe/public/assets/MenuImg/Milk Tea Latte.png
  fe/public/assets/MenuImg/Mint Chocolate.png
  fe/public/assets/MenuImg/Orange Carrot Juice.png
  fe/public/assets/MenuImg/Peach Earl Grey.png
  fe/public/assets/MenuImg/Peach Plum Sparkling .png
  fe/public/assets/MenuImg/Peach Strawberry Crush.png
  fe/public/assets/MenuImg/Peppermint.png
  fe/public/assets/MenuImg/Premium Blend Deep Latte.png
  fe/public/assets/MenuImg/Red Grapefruit Tea.png
  fe/public/assets/MenuImg/Ristretto Delight.png
  fe/public/assets/MenuImg/Strawberry Smoothie.png
  fe/public/assets/MenuImg/Tomato Juice.png
  fe/public/assets/MenuImg/Vanilla Delight.png
  fe/public/assets/MenuImg/Watermelon Cooler Smoothie.png
  fe/public/assets/MenuImg/White Chocolate.png
  fe/public/assets/MenuImg/Yuzu Chamomile.png
  fe/public/assets/MenuImg/Yuzu Grapefruit Sparkling .png
  fe/public/assets/MenuImg/jeju Hanrabong tangerine tea.png
  fe/public/data/menus.json
  fe/public/index.html
  fe/public/manifest.json
  fe/public/robots.txt
  fe/src/App.css
  fe/src/App.tsx
  fe/src/index.tsx
  fe/src/setupTests.ts
  fe/src/styles/common.css
  fe/src/styles/index.css
  fe/src/styles/reset.css
  fe/src/styles/theme.css
  fe/tsconfig.json
  fe/yarn.lock
Labels: 🍹 FE, 🔧 chore

#18 [BE/Sprint #1] CI/CD 환경 구성
  .github/workflows/cicd.yml
  be/appspec.yml
  be/autodeploy.sh
Labels: ☕️ BE, 🚨 HIGH

#11 [BE] 메뉴 API 서버 구현
  be/.gitignore
  be/build.gradle
  be/src/main/java/com/kiosk/domain/entity/Category.java
  be/src/main/java/com/kiosk/domain/entity/CategoryType.java
  be/src/main/java/com/kiosk/domain/entity/Product.java
  be/src/main/java/com/kiosk/domain/repository/CategoryRepository.java
  be/src/main/java/com/kiosk/domain/repository/JdbcCategoryRepository.java
  be/src/main/java/com/kiosk/domain/repository/JdbcProductRepository.java
  be/src/main/java/com/kiosk/domain/repository/MemoryProductRepository.java
  be/src/main/java/com/kiosk/domain/repository/ProductRepository.java
  be/src/main/java/com/kiosk/web/controller/MenuController.java
  be/src/main/java/com/kiosk/web/controller/TestController.java
  be/src/main/java/com/kiosk/web/controller/dto/MenuCategoryResponse.java
  be/src/main/java/com/kiosk/web/controller/dto/MenuDto.java
  be/src/main/java/com/kiosk/web/service/CategoryService.java
  be/src/main/java/com/kiosk/web/service/ProductService.java
  be/src/main/resources/application.properties
  be/src/test/java/com/kiosk/domain/repository/JdbcProductRepositoryTest.java
  be/src/test/java/com/kiosk/domain/repository/MemoryProductRepositoryTest.java
Labels: ☕️ BE, 🚨 HIGH, feat

#22 [BE/Spring #1] dev-be 브랜치 빌드 실패 문제 해결
  be/build.gradle
  be/src/test/java/com/kiosk/domain/repository/test.sql
Labels: 🐛 Bug

#38 [BE] README에 백엔드 정보 업데이트
  README.md
Labels: 📝 docs

#39 [BE] 백엔드 서버 CORS 구현
  be/src/main/java/com/kiosk/config/WebConfig.java
Labels: ☕️ BE, MEDIUM, Sprint #1

#41 [FE/Sprint #1] 메인 페이지 주요 기능
  README.md
  fe/public/data/categories.json
  fe/public/data/menus.json
  fe/public/favicon.ico
  fe/public/index.html
  fe/public/manifest.json
  fe/src/App.css
  fe/src/App.tsx
  fe/src/components/Main/Main.module.css
  fe/src/components/Main/Main.tsx
  fe/src/components/Main/MenuItem.tsx
  fe/src/components/Main/OrderArea.tsx
  fe/src/components/Main/index.ts
  fe/src/components/Modal/OrderModal.module.css
  fe/src/components/Modal/OrderModal.tsx
  fe/src/components/Navbar/CategoryButton.tsx
  fe/src/components/Navbar/CategoryNavbar.module.css
  fe/src/components/Navbar/CategoryNavbar.tsx
  fe/src/components/Navbar/index.ts
  fe/src/index.tsx
  fe/src/menuOrderReducer.ts
  fe/src/pages/MainPage.tsx
  fe/src/pages/types.ts
  fe/src/styles/theme.css
  fe/src/types/index.d.ts
  fe/src/utils/index.ts
  fe/tsconfig.json
Labels: 🍹 FE

#32 [BE/Sprint #1] CI/CD 환경 구축 및 메뉴 API 구현
  .github/workflows/cicd.yml
  be/.gitignore
  be/appspec.yml
  be/autodeploy.sh
  be/build.gradle
  be/gradle/wrapper/gradle-wrapper.jar
  be/gradle/wrapper/gradle-wrapper.properties
  be/gradlew
  be/gradlew.bat
  be/settings.gradle
  be/src/main/java/com/kiosk/KioskWebApplication.java
  be/src/main/java/com/kiosk/config/WebConfig.java
  be/src/main/java/com/kiosk/domain/entity/Category.java
  be/src/main/java/com/kiosk/domain/entity/CategoryType.java
  be/src/main/java/com/kiosk/domain/entity/Product.java
  be/src/main/java/com/kiosk/domain/repository/CategoryRepository.java
  be/src/main/java/com/kiosk/domain/repository/JdbcCategoryRepository.java
  be/src/main/java/com/kiosk/domain/repository/JdbcProductRepository.java
  be/src/main/java/com/kiosk/domain/repository/MemoryProductRepository.java
  be/src/main/java/com/kiosk/domain/repository/ProductRepository.java
  be/src/main/java/com/kiosk/web/controller/MenuController.java
  be/src/main/java/com/kiosk/web/controller/TestController.java
  be/src/main/java/com/kiosk/web/controller/dto/MenuCategoryResponse.java
  be/src/main/java/com/kiosk/web/controller/dto/MenuDto.java
  be/src/main/java/com/kiosk/web/service/CategoryService.java
  be/src/main/java/com/kiosk/web/service/ProductService.java
  be/src/main/resources/application.properties
  be/src/test/java/com/kiosk/KioskWebApplicationTests.java
  be/src/test/java/com/kiosk/domain/repository/JdbcProductRepositoryTest.java
  be/src/test/java/com/kiosk/domain/repository/MemoryProductRepositoryTest.java
  be/src/test/java/com/kiosk/domain/repository/test.sql
  pull_request_template.md
Labels: ☕️ BE, 🚨 HIGH, Sprint #1, 📝 docs

#45 [BE] menu -> product 네이밍 수정
  be/src/main/java/com/kiosk/domain/repository/JdbcProductRepository.java
  be/src/main/java/com/kiosk/domain/repository/MemoryProductRepository.java
  be/src/main/java/com/kiosk/domain/repository/ProductRepository.java
  be/src/main/java/com/kiosk/web/controller/ProductController.java
  be/src/main/java/com/kiosk/web/controller/TestController.java
  be/src/main/java/com/kiosk/web/controller/dto/ProductCategoryResponse.java
  be/src/main/java/com/kiosk/web/controller/dto/ProductDto.java
  be/src/main/java/com/kiosk/web/service/ProductService.java
  be/src/test/java/com/kiosk/domain/repository/JdbcProductRepositoryTest.java
  be/src/test/java/com/kiosk/domain/repository/MemoryProductRepositoryTest.java
Labels: ☕️ BE, ↓ LOW, 🧹 refactor

#61 [FE/Sprint #2] 카드 결제 로딩 인디케이터 구현
  fe/src/components/Modal/PaymentIndicator.module.css
  fe/src/components/Modal/PaymentIndicator.tsx
Labels: 🍹 FE, MEDIUM, feat, Sprint #2

#63 [FE] 결제 방식 선택 모달
  fe/src/App.css
  fe/src/App.tsx
  fe/src/api/index.ts
  fe/src/components/Main/Cart.tsx
  fe/src/components/Main/Main.module.css
  fe/src/components/Main/Main.tsx
  fe/src/components/Modal/Modal.module.css
  fe/src/components/Modal/OrderModal.module.css
  fe/src/components/Modal/OrderModal.tsx
  fe/src/components/Modal/PaymentModalContent.module.css
  fe/src/components/Modal/PaymentModalContent.tsx
  fe/src/components/Navbar/CategoryButton.tsx
  fe/src/components/Navbar/CategoryNavbar.tsx
  fe/src/pages/MainPage.module.css
  fe/src/pages/MainPage.tsx
  fe/src/pages/types.ts
  fe/src/utils/index.ts
Labels: 🍹 FE

#62 [BE] 컴포넌트 추가 (OrderProduct, Orders, OrderLog 관련)
  be/src/main/java/com/kiosk/api/product/domain/entity/OrderLog.java
  be/src/main/java/com/kiosk/api/product/domain/entity/OrderProduct.java
  be/src/main/java/com/kiosk/api/product/domain/entity/Orders.java
  be/src/main/java/com/kiosk/api/product/domain/repository/JdbcOrderLogRepositoryImpl.java
  be/src/main/java/com/kiosk/api/product/domain/repository/JdbcOrderProductRepositoryImpl.java
  be/src/main/java/com/kiosk/api/product/domain/repository/JdbcOrdersRepositoryImpl.java
  be/src/main/java/com/kiosk/api/product/domain/repository/OrderLogRepository.java
  be/src/main/java/com/kiosk/api/product/domain/repository/OrderProductRepository.java
  be/src/main/java/com/kiosk/api/product/domain/repository/OrdersRepository.java
  be/src/main/java/com/kiosk/api/product/web/controller/dto/OrderProductResponseDto.java
  be/src/main/java/com/kiosk/api/product/web/service/OrderLogService.java
Labels: ☕️ BE, 🚨 HIGH, 🔧 chore, feat, Sprint #2

#60 [BE] 상품 테스트 코드 구현
  be/build.gradle
  be/src/main/java/com/kiosk/api/product/web/controller/dto/ProductCategoryResponse.java
  be/src/test/java/com/kiosk/api/product/web/controller/ProductControllerTest.java
  be/src/test/java/com/kiosk/domain/repository/JdbcProductRepositoryTest.java
  be/src/test/java/com/kiosk/domain/repository/MemoryProductRepositoryTest.java
  be/src/test/java/com/kiosk/domain/repository/test.sql
  be/src/test/resources/application-test.properties
  be/src/test/resources/db/h2/data.sql
  be/src/test/resources/db/h2/schema.sql
Labels: ☕️ BE, MEDIUM, 🔧 chore, Sprint #2

#65 [BE] Order Repository 기능 구현
  be/src/main/java/com/kiosk/api/order/domain/dto/OrderProductResponseDto.java
  be/src/main/java/com/kiosk/api/order/domain/entity/OrderLog.java
  be/src/main/java/com/kiosk/api/order/domain/entity/OrderProduct.java
  be/src/main/java/com/kiosk/api/order/domain/entity/Orders.java
  be/src/main/java/com/kiosk/api/order/domain/repository/JdbcOrderLogRepositoryImpl.java
  be/src/main/java/com/kiosk/api/order/domain/repository/JdbcOrderProductRepositoryImpl.java
  be/src/main/java/com/kiosk/api/order/domain/repository/JdbcOrdersRepositoryImpl.java
  be/src/main/java/com/kiosk/api/order/domain/repository/OrderLogRepository.java
  be/src/main/java/com/kiosk/api/order/domain/repository/OrderProductRepository.java
  be/src/main/java/com/kiosk/api/order/domain/repository/OrdersRepository.java
  be/src/main/java/com/kiosk/api/product/domain/entity/OrderProduct.java
  be/src/main/java/com/kiosk/api/product/domain/repository/JdbcOrderLogRepositoryImpl.java
  be/src/main/java/com/kiosk/api/product/domain/repository/JdbcOrderProductRepositoryImpl.java
  be/src/main/java/com/kiosk/api/product/domain/repository/OrderLogRepository.java
  be/src/main/java/com/kiosk/api/product/domain/repository/OrderProductRepository.java
  be/src/main/java/com/kiosk/api/product/domain/repository/OrdersRepository.java
  be/src/main/java/com/kiosk/api/product/web/service/OrderLogService.java
Labels: ☕️ BE, 🚨 HIGH, Sprint #2

#67 [FE] 영수증 페이지 구현
  fe/src/components/Receipt.tsx
  fe/src/components/Receipt/Receipt.module.css
  fe/src/components/Receipt/Receipt.tsx
  fe/src/pages/ReceiptPage.module.css
  fe/src/pages/ReceiptPage.tsx
  fe/src/pages/types.ts
  fe/src/utils/index.ts
Labels: 🍹 FE, 🚨 HIGH, feat

#69 [BE] 결제 관련 레포지토리, 비지니스 구현
  be/src/main/java/com/kiosk/api/payment/controller/PaymentCardController.java
  be/src/main/java/com/kiosk/api/payment/controller/PaymentCashController.java
  be/src/main/java/com/kiosk/api/payment/controller/PaymentController.java
  be/src/main/java/com/kiosk/api/payment/domain/dto/PaymentDto.java
  be/src/main/java/com/kiosk/api/payment/domain/dto/PaymentRequestDto.java
  be/src/main/java/com/kiosk/api/payment/domain/entity/Payment.java
  be/src/main/java/com/kiosk/api/payment/domain/repository/PaymentCardRepository.java
  be/src/main/java/com/kiosk/api/payment/domain/repository/PaymentCashRepository.java
  be/src/main/java/com/kiosk/api/payment/domain/repository/PaymentRepository.java
  be/src/main/java/com/kiosk/api/payment/domain/repository/PaymentRepositoryImpl.java
  be/src/main/java/com/kiosk/api/payment/service/PaymentCardService.java
  be/src/main/java/com/kiosk/api/payment/service/PaymentCashService.java
Labels: ☕️ BE, 🚨 HIGH, feat, Sprint #2

#72 [BE] OrdersRepository 기능 구현, PaymentRepository 변경
  be/src/main/java/com/kiosk/api/order/domain/entity/Orders.java
  be/src/main/java/com/kiosk/api/order/domain/repository/JdbcOrdersRepositoryImpl.java
  be/src/main/java/com/kiosk/api/order/domain/repository/OrdersRepository.java
  be/src/main/java/com/kiosk/api/payment/domain/dto/PaymentRequestDto.java
  be/src/main/java/com/kiosk/api/payment/domain/entity/Payment.java
  be/src/main/java/com/kiosk/api/payment/domain/repository/PaymentRepository.java
  be/src/main/java/com/kiosk/api/payment/domain/repository/PaymentRepositoryImpl.java
Labels: ☕️ BE, MEDIUM, 🔧 chore

#74 [BE] 영수증 API 개발
  be/src/main/java/com/kiosk/api/order/domain/dto/OrderProductResponseDto.java
  be/src/main/java/com/kiosk/api/order/domain/dto/OrdersResponseDto.java
  be/src/main/java/com/kiosk/api/order/domain/entity/OrderProduct.java
  be/src/main/java/com/kiosk/api/order/domain/repository/JdbcOrderProductRepositoryImpl.java
  be/src/main/java/com/kiosk/api/payment/domain/dto/PaymentRequestDto.java
  be/src/main/java/com/kiosk/api/payment/domain/dto/PaymentResponseDto.java
  be/src/main/java/com/kiosk/api/payment/domain/entity/PaymentMethod.java
  be/src/main/java/com/kiosk/api/receipt/controller/ReceiptController.java
  be/src/main/java/com/kiosk/api/receipt/domain/dto/ReceiptResponseDto.java
  be/src/main/java/com/kiosk/api/receipt/domain/dto/RecieptDto.java
  be/src/main/java/com/kiosk/api/receipt/domain/entity/Receipt.java
  be/src/main/java/com/kiosk/api/receipt/domain/repository/ReceiptRepository.java
  be/src/main/java/com/kiosk/api/receipt/service/ReceiptService.java
Labels: ☕️ BE, 🚨 HIGH, Sprint #2

#73 [FE] 결제 요청 후 영수증 페이지로 렌더링, 전반 리팩토링
  fe/src/App.css
  fe/src/App.tsx
  fe/src/api/index.ts
  fe/src/components/LoadingIndicator/LoadingIndicator.module.css
  fe/src/components/LoadingIndicator/LoadingIndicator.tsx
  fe/src/components/Main/Cart.tsx
  fe/src/components/Main/Main.module.css
  fe/src/components/Main/Main.tsx
  fe/src/components/Main/MenuItem.tsx
  fe/src/components/Modal/Modal.module.css
  fe/src/components/Modal/OrderModal.module.css
  fe/src/components/Modal/OrderModal.tsx
  fe/src/components/Modal/PaymentModalContent.tsx
  fe/src/components/Navbar/CategoryNavbar.module.css
  fe/src/components/Receipt.tsx
  fe/src/components/Receipt/Receipt.module.css
  fe/src/components/Receipt/Receipt.tsx
  fe/src/components/atoms/Button.tsx
  fe/src/hooks/useOutsideClick.ts
  fe/src/hooks/useProducts.ts
  fe/src/menuOrderReducer.ts
  fe/src/pages/Home.module.css
  fe/src/pages/Home.tsx
  fe/src/pages/MainPage.tsx
  fe/src/pages/ReceiptPage.module.css
  fe/src/pages/ReceiptPage.tsx
  fe/src/pages/types.ts
  fe/src/utils/index.ts
Labels: 🍹 FE, 🧹 refactor, Sprint #2

#75 [BE] API 테스트 코드 구현
  be/src/main/java/com/kiosk/api/payment/controller/PaymentController.java
  be/src/main/java/com/kiosk/api/payment/domain/dto/PaymentRequestDto.java
  be/src/main/java/com/kiosk/api/payment/domain/dto/PaymentResultResponseDto.java
  be/src/main/java/com/kiosk/api/payment/domain/repository/PaymentRepository.java
  be/src/main/java/com/kiosk/api/payment/domain/repository/PaymentRepositoryImpl.java
  be/src/main/java/com/kiosk/api/product/domain/repository/JdbcProductRepository.java
  be/src/main/java/com/kiosk/api/receipt/controller/ReceiptController.java
  be/src/main/java/com/kiosk/api/receipt/domain/dto/ReceiptResponseDto.java
  be/src/main/java/com/kiosk/api/receipt/service/ReceiptService.java
  be/src/test/java/com/kiosk/KioskWebApplicationTests.java
  be/src/test/java/com/kiosk/api/payment/controller/PaymentControllerTest.java
  be/src/test/java/com/kiosk/api/payment/domain/repository/PaymentRepositoryImplTest.java
  be/src/test/java/com/kiosk/api/receipt/controller/ReceiptControllerTest.java
  be/src/test/resources/application-test.properties
  be/src/test/resources/db/h2/data.sql
  be/src/test/resources/db/h2/schema.sql
Labels: ☕️ BE, MEDIUM, Sprint #2

#81 [FE] 재확인 모달 구현 및 적용
  fe/src/components/Main/Cart.tsx
  fe/src/components/Modal/ConfirmModal.module.css
  fe/src/components/Modal/ConfirmModal.tsx
  fe/src/components/Modal/Modal.module.css
  fe/src/components/Modal/OrderModal.module.css
  fe/src/components/Modal/PaymentModalContent.tsx
  fe/src/styles/theme.css
Labels: 🍹 FE, MEDIUM, feat, Sprint #2

#82 [BE] order_number에 필요한 로직 구현
  be/src/main/java/com/kiosk/api/order/domain/entity/OrderLog.java
  be/src/main/java/com/kiosk/api/order/domain/entity/Orders.java
  be/src/main/java/com/kiosk/api/order/domain/repository/JdbcOrderLogRepositoryImpl.java
  be/src/main/java/com/kiosk/api/order/domain/repository/JdbcOrderProductRepositoryImpl.java
  be/src/main/java/com/kiosk/api/order/domain/repository/JdbcOrdersRepositoryImpl.java
  be/src/main/java/com/kiosk/api/order/domain/repository/OrderLogRepository.java
  be/src/main/java/com/kiosk/api/order/domain/repository/OrderProductRepository.java
  be/src/main/java/com/kiosk/api/order/domain/repository/OrdersRepository.java
  be/src/main/java/com/kiosk/api/order/domain/service/OrderLogService.java
  be/src/main/java/com/kiosk/api/payment/controller/PaymentController.java
  be/src/main/java/com/kiosk/api/payment/service/PaymentService.java
  be/src/main/java/com/kiosk/api/product/domain/entity/Product.java
  be/src/main/java/com/kiosk/api/product/domain/repository/JdbcProductRepository.java
  be/src/main/java/com/kiosk/api/product/domain/repository/MemoryProductRepository.java
  be/src/main/java/com/kiosk/api/product/domain/repository/ProductRepository.java
  be/src/main/java/com/kiosk/api/product/web/controller/dto/ProductDto.java
  be/src/test/java/com/kiosk/api/product/web/controller/ProductControllerTest.java
  be/src/test/java/com/kiosk/domain/repository/JdbcProductRepositoryTest.java
Labels: ☕️ BE, 🚨 HIGH, feat

#84 [FE] Receipt Page 리팩토링
  fe/src/components/Receipt/Receipt.tsx
  fe/src/pages/ReceiptPage.module.css
  fe/src/pages/ReceiptPage.tsx
  fe/src/pages/types.ts
  fe/src/utils/index.ts
Labels: 🍹 FE, Sprint #2

#85 [BE] dailyActions, dailyReset 테스트 코드 구현
  be/src/main/java/com/kiosk/api/order/domain/entity/OrderLog.java
  be/src/main/java/com/kiosk/api/order/domain/repository/JdbcOrderLogRepositoryImpl.java
  be/src/main/java/com/kiosk/api/order/domain/repository/JdbcOrderProductRepositoryImpl.java
  be/src/main/java/com/kiosk/api/order/domain/repository/JdbcOrdersRepositoryImpl.java
  be/src/main/java/com/kiosk/api/order/domain/repository/OrderLogRepository.java
  be/src/main/java/com/kiosk/api/product/domain/repository/JdbcProductRepository.java
  be/src/main/java/com/kiosk/api/product/web/service/OrderLogService.java
  be/src/test/java/com/kiosk/api/order/domain/repository/JdbcOrdersRepositoryImplTest.java
  be/src/test/java/com/kiosk/api/order/domain/service/OrderLogServiceTest.java
Labels: ☕️ BE, 🚨 HIGH, 🐛 Bug, feat, Sprint #2

#86 [BE] 디렉토리 구조 변경
  be/src/main/java/com/kiosk/api/order/service/OrderLogService.java
  be/src/main/java/com/kiosk/api/product/controller/ProductController.java
  be/src/main/java/com/kiosk/api/product/controller/TestController.java
  be/src/main/java/com/kiosk/api/product/controller/dto/ProductCategoryResponse.java
  be/src/main/java/com/kiosk/api/product/controller/dto/ProductDto.java
  be/src/main/java/com/kiosk/api/product/service/CategoryService.java
  be/src/main/java/com/kiosk/api/product/service/OrderLogService.java
  be/src/main/java/com/kiosk/api/product/service/ProductService.java
  be/src/test/java/com/kiosk/domain/repository/MemoryProductRepositoryTest.java
Labels: ☕️ BE

#88 [BE] Orders, Payment 비즈니스 로직 구현
  be/src/main/java/com/kiosk/api/order/domain/entity/Orders.java
  be/src/main/java/com/kiosk/api/order/domain/repository/JdbcOrdersRepositoryImpl.java
  be/src/main/java/com/kiosk/api/order/service/OrderLogService.java
  be/src/main/java/com/kiosk/api/order/service/OrderProductService.java
  be/src/main/java/com/kiosk/api/order/service/OrdersService.java
  be/src/main/java/com/kiosk/api/payment/controller/PaymentController.java
  be/src/main/java/com/kiosk/api/payment/domain/dto/PaymentRequestDto.java
  be/src/main/java/com/kiosk/api/payment/service/PaymentService.java
  be/src/main/java/com/kiosk/api/product/domain/repository/JdbcProductRepository.java
  be/src/main/java/com/kiosk/api/product/domain/repository/MemoryProductRepository.java
  be/src/main/java/com/kiosk/api/product/domain/repository/ProductRepository.java
  be/src/main/java/com/kiosk/api/product/service/OrderLogService.java
  be/src/main/java/com/kiosk/api/product/service/ProductService.java
Labels: ☕️ BE, 🚨 HIGH, feat

#87 [FE] 메뉴 담기 모달 수정
  fe/public/assets/icon/drink.png
  fe/src/components/Modal/CashPayment.tsx
  fe/src/components/Modal/ConfirmModal.tsx
  fe/src/components/Modal/OrderModal/MenuOption.tsx
  fe/src/components/Modal/OrderModal/OrderModal.module.css
  fe/src/components/Modal/OrderModal/OrderModal.tsx
  fe/src/components/atoms/Button.tsx
  fe/src/styles/theme.css
Labels: 🍹 FE, ↓ LOW, 🧹 refactor, Sprint #2

#94 [FE] 카테고리 변경 시 메뉴 슬라이딩 애니메이션 효과
  fe/src/components/Main/Cart.module.css
  fe/src/components/Main/Main.tsx
  fe/src/components/Navbar/CategoryNavbar.module.css
  fe/src/pages/Home.module.css
  fe/src/pages/Home.tsx
Labels: 🍹 FE

#91 [FE] 카테고리 네비바 스크롤 기능 및 3개의 카테고리 노출
  fe/src/components/Navbar/CategoryNavbar.module.css
Labels: 🍹 FE, feat

#95 [FE] Sprint #02 작업
  fe/package.json
  fe/public/assets/icon/drink.png
  fe/src/App.css
  fe/src/App.tsx
  fe/src/api/index.ts
  fe/src/components/LoadingIndicator/LoadingIndicator.module.css
  fe/src/components/LoadingIndicator/LoadingIndicator.tsx
  fe/src/components/Main/Cart.module.css
  fe/src/components/Main/Cart.tsx
  fe/src/components/Main/Main.module.css
  fe/src/components/Main/Main.tsx
  fe/src/components/MenuItem/MenuItem.module.css
  fe/src/components/MenuItem/MenuItem.tsx
  fe/src/components/MenuItem/index.tsx
  fe/src/components/Modal/CashPayment.module.css
  fe/src/components/Modal/CashPayment.tsx
  fe/src/components/Modal/ConfirmModal.module.css
  fe/src/components/Modal/ConfirmModal.tsx
  fe/src/components/Modal/Modal.module.css
  fe/src/components/Modal/OrderModal.module.css
  fe/src/components/Modal/OrderModal.tsx
  fe/src/components/Modal/OrderModal/AddButton.tsx
  fe/src/components/Modal/OrderModal/MenuOption.tsx
  fe/src/components/Modal/OrderModal/OrderModal.module.css
  fe/src/components/Modal/OrderModal/OrderModal.tsx
  fe/src/components/Modal/OrderModal/index.tsx
  fe/src/components/Modal/PaymentModalContent.module.css
  fe/src/components/Modal/PaymentModalContent.tsx
  fe/src/components/Navbar/CategoryButton.tsx
  fe/src/components/Navbar/CategoryNavbar.module.css
  fe/src/components/Navbar/CategoryNavbar.tsx
  fe/src/components/Receipt.tsx
  fe/src/components/Receipt/Receipt.module.css
  fe/src/components/Receipt/Receipt.tsx
  fe/src/components/atoms/Button.tsx
  fe/src/constant.ts
  fe/src/hooks/useOutsideClick.ts
  fe/src/hooks/useProducts.ts
  fe/src/menuOrderReducer.ts
  fe/src/pages/Home.module.css
  fe/src/pages/Home.tsx
  fe/src/pages/MainPage.tsx
  fe/src/pages/ReceiptPage.module.css
  fe/src/pages/ReceiptPage.tsx
  fe/src/pages/types.ts
  fe/src/styles/theme.css
  fe/src/utils/index.ts
  fe/yarn.lock
Labels: 🍹 FE
